#!/usr/bin/env bash
taskcolor="\033[0;30;107m"
taskcolorDim="\033[2;30;107m"
activitycolor="\033[44;93m"
fragmentcolor="\033[95m"
infocolor="\033[36m"
objectcolor="\033[2m"
packagecolor="\033[36;2m"
reset="\033[0m"

DIR=$(dirname "$0")
versionFile="$DIR/.version"

timestamp=$(date +%s)
dsFileName=".ds_temp_file_$timestamp"
simpleFile=".ds_temp_simple_file_$timestamp"
mapFile=".ds_temp_map_file_$timestamp"
keepFile=false
useSpecificFile=""

#TODO:
# Turns out that applications have fragments like this:
# ······#1:·RestaurantListContent{2602624·#1·id=0x7f0a00f1·RestaurantListContent}$
# DEALT with above ^ DONE
#1. Also pull out fragment TAGs from original line...
#    mTag from line below the original
#2. Also pull out fragent mState list below: from 2 lines below original
#    static final int INVALID_STATE = -1;   // Invalid state used as a null value.
#    static final int INITIALIZING = 0;     // Not yet created.
#    static final int CREATED = 1;          // Created.
#    static final int ACTIVITY_CREATED = 2; // The activity has finished its creation.
#    static final int STOPPED = 3;          // Fully created, not started.
#    static final int STARTED = 4;          // Created and started, not resumed.
#    static final int RESUMED = 5;          // Created started and resumed.
#What is state 7?

while getopts khf:v flag
do
    case "${flag}" in
        h) 
            echo "TODO: Print help"
            exit 0
        ;;
        v)
            echo "Easy-Dumpsys Version: $(cat "$versionFile")"
            exit 0
        ;;
        k) 
            echo "Keeping the file: $dsFileName"
            printf "${infocolor}Keeping the file: ${dsFileName}${reset}\n"
            keepFile=true
            shift 1
        ;;
        f) 
            useSpecificFile="${OPTARG}"
            printf "${infocolor}Using a specific file instead: ${useSpecificFile}${reset}\n"
            shift 2
        ;;
    esac
done

package=$1
if [ $# -eq 0 ] && [ -z "$useSpecificFile" ]; then
    fzf_installed=$(which fzf)
    if [[ -z ${fzf_installed} ]]; then
        echo "FZF is NOT installed so you can not use the interactive package picker"
        echo "Install FZF to enable this feature"
        exit 1
    else
        packToUse=$(adb shell pm list package -3 | fzf | cut -d':' -f2)
        echo "Using package: $packToUse"
        package="$packToUse"
        if [[ -z "$package" ]]; then
            echo "No package provided!"
            exit 1
        fi
    fi
fi

# The all important adb dumpsys command
if [[ -z "$useSpecificFile" ]]; then
    adb shell dumpsys activity "$package" > "$dsFileName"
else
    cat "$useSpecificFile" > "$dsFileName"
fi

sed -i '' '/Added\ Fragments\:/,/FragmentManager\ misc\ state\:/d' "$dsFileName"
sed -i '' '/Child\ FragmentManager/d' "$dsFileName"

lineIterator=0
while IFS= read -r line
do
#TODO Tasks
#TASK 10273:com.babbel.mobile.android.en id=154 userId=0
    lineIterator=$((lineIterator + 1))
    #elif [[ "$line" =~ [[:space:]]{2,}[a-zA-Z1-9]+\{[a-z0-9]+\}\ \( ]]; then
    #delete all lines Added Fragments:
    # and FragmentManager misc state: 
    #sed '/Added\ Fragments\:/,/FragmentManager\ misc/d'
    #find spaces and 
    #\ [a-zA-Z0-9]*\{[0-9a-z\}]*\ .*-.*-.*-.*-
	#elif [[ "$line" =~ \ [a-zA-Z1-9]+\{[a-z0-9\}]+\ .*id\= ]]; then
    if [[ "$line" =~ "TASK".*  ]]; then
		#16-03-2021 - Adding task seems to work fine doesnt break anything
		echo "$line" >> "$simpleFile"
    elif [[ "$line" =~ "  ACTIVITY".* ]]; then
        echo "$line" >> "$simpleFile"
        statusLine=$(sed -n "$((lineIterator + 2))p" "$dsFileName")
        echo "### $statusLine" >> "$simpleFile"
    elif [[ "$line" =~ \ [a-zA-Z1-9]+\{[a-z0-9\}]+\  ]]; then
        #TODO fragmetns not picked up here
        echo "$line" >> "$simpleFile"
    fi
done < "$dsFileName"

#TASK 10273:com.babbel.mobile.android.en id=154 userId=0
#  ACTIVITY com.babbel.mobile.android.en/com.babbel.mobile.android.core.presentation.mainactivity.screens.MainActivity b335371 pid=19503
####       mResumed=false mStopped=true mFinished=false
#        #0: ReportFragment{a95b7f6 #0 androidx.lifecycle.LifecycleDispatcher.report_fragment_tag}
#      mCreated=true mResumed=false mStopped=true    Active Fragments:    OnboardingScreen{f912a8} (16cc3757-abaf-4e41-b243-e366c7302bed) id=0x7f0a0199 com.babbel.mobile.android.core.presentation.onboarding.screens.OnboardingScreen}
#          Active Fragments:          OnboardingPageScreen{cd9b8a7} (ff4989e6-aaf6-4360-91cc-6acefc360b5f) id=0x7f0a0587}
#          OnboardingPageScreen{a1959f2} (82ed986a-86e3-4880-9c03-a559d645ca8e) id=0x7f0a0587}
#    SplashScreen{d5f233e} (215e56df-c30f-4597-878f-5d2d7bb5d2f7) id=0x7f0a0199 com.babbel.mobile.android.core.presentation.splashscreen.screens.SplashScreen}
#    SupportRequestManagerFragment{e6f9ab5} (d7773d64-f823-4cc6-a560-f28e8fa8098b) com.bumptech.glide.manager}{parent=null}
#TASK 10273:com.babbel.mobile.android.en id=154 userId=0
#  ACTIVITY com.babbel.mobile.android.en/com.babbel.mobile.android.core.presentation.devconfig.view.DevConfigActivity 513f114 pid=19503
####       mResumed=true mStopped=false mFinished=false
#        #0: ReportFragment{63a64dc #0 androidx.lifecycle.LifecycleDispatcher.report_fragment_tag}
#      mCreated=true mResumed=true mStopped=false    Active Fragments:    OverrideFragment{78233f7} (65ce9eee-8930-4681-9b32-5ba0abb9b89a) f0}


declare -A activityMap
levelOneConstant=10
levelIterator=6
activityCounter=0
simpleLineIterator=0
while IFS= read -r line
do
    level=0
    simpleLineIterator=$((simpleLineIterator + 1))
    if [[ "$line" =~ "TASK".* ]]; then
        taskName=$(echo "$line" | awk '{print $2}' | cut -d':' -f2)
        echo "T $taskName - -" >> "$mapFile"
    elif [[ "$line" =~ "  ACTIVITY".* ]]; then
        activityCounter=$((activityCounter+1))
        activityDisplayLine=$(printf "$line" | sed -e 's/^[[:space:]]*//' | cut -d' ' -f2 | cut -d'/' -f2)
        activityStateLine=$(sed -n "$((simpleLineIterator + 1))p" "$simpleFile")
        SAVEIFS=$IFS
        IFS=' ' read -r -a array <<< "$activityStateLine"
        IFS=$SAVEIFS
        resumedPreManip=$(printf "${array[1]}" | cut -d'=' -f2)
        ext="-"
        if [[ "$resumedPreManip" == true ]]; then
            ext="Active" 
        fi
        echo "A $activityDisplayLine $ext -" >> "$mapFile"
        activityMap["$activityCounter"]="$simpleLineIterator"
    #elif [[ "$line" =~ [[:space:]]{2,}[a-zA-Z1-9]+\{[a-z0-9]+\}\ \( ]]; then
    #elif [[ "$line" =~ \ [a-zA-Z1-9]+\{[a-z0-9\}]+\ .*id\= ]]; then
    elif [[ "$line" =~ \ [a-zA-Z1-9]+\{[a-z0-9\}]+\  ]]; then
        numberOfSpace=$(printf "$line" | awk -F'[^ ]' '{print length($1),NR}' | awk '{print $1}')
        #if [[ ! "$numberOfSpace" == 4 ]] && [[ ! "$numberOfSpace" == 6 ]]; then
        if [[ ! "$numberOfSpace" == 4 ]] && [[ ! "$numberOfSpace" == 6 ]] && [[ ! "$numberOfSpace" == 8 ]]; then
            levelA=$((numberOfSpace - levelOneConstant))
            levelB=$((levelA / levelIterator))
            level=$((levelB + 1))
        fi
        wholeFragment=$(printf "$line" | perl -nle 'm/([a-zA-Z0-9]*{[a-z0-9}]*)/; print $1')
        externalPackager=$(printf "$line" | perl -nle 'm/([a-z0-9A-Z_]*(\.[A-Za-z0-9_]+)+[A-Z0-9a-z_]*)/; print $1')
        if [[ -z "$externalPackager" ]]; then
            echo "F $wholeFragment $level -" >> "$mapFile"
        else
            echo "F $wholeFragment $level $externalPackager" >> "$mapFile"
        fi
    else
        echo "- - - -" >> "$mapFile"
    fi
done < "$simpleFile"

declare -A barMap
totalLineCount=$(cat "$simpleFile" | wc -l | sed 's/[[:space:]]//g')
finalLineIterator=0
currentActivtyNum=0
while IFS= read -r line
do
    finalLineIterator=$((finalLineIterator + 1))
    part1=$(echo "$line" | awk '{print $1}')
    part2=$(echo "$line" | awk '{print $2}')
    part3=$(echo "$line" | awk '{print $3}')
    part4=$(echo "$line" | awk '{print $4}')
    if [[ "$part1" == "T" ]]; then
        echo ""
        #printf "TASK: ${taskcolor}---> $part2 <---${reset}\n"
        printf "${taskcolorDim}--->${taskcolor} $part2 ${taskcolorDim}<---${reset}\n"
    elif [[ "$part1" == "A" ]]; then
        unset barMap
        currentActivtyNum=$((currentActivtyNum+1))
        activeStatus=""
        if [[ "$part3" == "Active" ]]; then
            activeStatus=" - \033[93mActive\033[0m"
        fi
        echo ""
        printf "${activitycolor}$part2${reset}${activeStatus}\n"
    elif [[ "$part1" == "F" ]]; then
        nextActLineNum=$((currentActivtyNum+1))
        nextActLine="${activityMap[$nextActLineNum]}"
        if [[ -z "$nextActLine" ]]; then
            nextActLine="$totalLineCount"
        else 
            #make it none inclusive
            nextActLine=$((nextActLine-1))
        fi
        linesLeftTillA=""
        finalLineIteratorAddOne=$((finalLineIterator + 1))
        if [[ "$finalLineIteratorAddOne" -le "$nextActLine" ]]; then
            linesLeftTillA=$(sed -n "${finalLineIteratorAddOne},${nextActLine}p" "$mapFile")
        fi

        if [[ ! -z "$linesLeftTillA" ]]; then
            while IFS= read -r inner
            do
                outter=$(echo "$inner" | awk '{print $3}')
                if [[ "$outter" == "$part3" ]]; then
                    #Still another at this level
                    barMap["$part3"]="y"
                    break
                else
                    barMap["$part3"]=""
                fi
            done < <(printf '%s\n' "$linesLeftTillA")
        else
            barMap["$part3"]=""
        fi
        
        for ((n=0;n<=$part3;n++))
        do
            if [[ "${barMap["$n"]}" == "y" ]]; then
                if [[ "$part3" == "$n" ]]; then
                    printf "├─ "
                else 
                    printf "│  "
                fi
            else
                if [[ "$part3" == "$n" ]]; then
                    printf "└─ "
                else 
                    printf "   "
                fi
            fi
        done
        #might not have closing bracket
        fr=$(printf "$part2" | cut -d'{' -f1)
        oc=$(printf "$part2" | cut -d'{' -f2 | sed 's/\}//g')
        #oc=$(printf "$part2" | cut -d'{' -f2 | cut -d'}' -f1)
        if [[ "$part4" != "-" ]]; then
            printf "${fragmentcolor}${fr}${reset} - ${objectcolor}${oc} ${packagecolor}(${part4})${reset}\n"
        else
            printf "${fragmentcolor}${fr}${reset} - ${objectcolor}${oc}${reset}\n"
        fi
    fi
done < "$mapFile"

printf "\n" 
if [[ "$keepFile" = false ]]; then
    rm "$dsFileName"
fi
rm "$simpleFile"
rm "$mapFile"
